In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
import pandas as pd
df = pd.read_csv("/content/gdrive/MyDrive/telugu_books.csv")

In [3]:
text = ' '.join(df['text'].astype(str))

In [4]:
print(text[:1000])


    సుశీలమ్మ కళ్ళలో భయం పారాడింది.
    "అనాధ బిడ్డ అని చిన్నప్పుడే తెలిస్తే మన దగ్గిరవాడు అలా అరమరిక లేకుండా చనువుగా పెరిగేవాడా?" పుట్టెడు దిగులు సుశీలమ్మ కంఠంలో పలికింది.
    "అది మనం పెంచేదాన్ని బట్టి వుంటుంది. అటువంటి బేధాలు మనలో లేనట్టు తెలుసుకొనేలా పెంచాలి."
    "చాలామంది అలాగే పెంచుతారు గదండీ."
    "ఏనాడో ఒకనాడు ఆ విషయం తెలియకపోదు. మనం పట్నంలో వుంటున్నాం గనక యింత కాలమయినా ఈ రహస్యాన్ని దాచగలిగాం.
    సుశీలమ్మ వింటూ కూర్చుంది.
    "ఒక వ్యక్తిత్వం అంటూ ఏర్పడ్డాక ఆ రహస్యం తెలిస్తే లోతుగా గాయపడతారు. అనేక ఆలోచనలు వస్తాయి. చిన్నప్పుడే తెలిస్తే అంతగా తలక్రిందులై పోరు" అన్నాడు.  
    "వాడు మనల్ని వదిలేసి వెళ్ళిపోతాడేమో!" అనలేక అంటున్న ఆమె గొంతులో ఏదో అడ్డుపడినట్టు ఉక్కిరిబిక్కిరి అయిపోతుంది.
    రామనాథానికి కూడా ఆ భయం లేకపోలేదు.
    ఆ భయాన్ని దాచుకుంటూ వెళ్ళడు. ఎలా వెళతాడు? ఎక్కడికి వెళతాడు? అసలు ఎందుకు వెళ్ళాలి? వాడికి మనమేం తక్కువ చేశామని వెళ్తాడు?" అన్నాడు.
    సుశీలమ్మకు ఎక్కడికో లోతు తెలియని అగాధంలోకి పడుతున్న వ్యక్తికి జారుడుమెట్లు చేతికి అందినట్టు అనిపించింది.   
    "


In [5]:
print("The number of characters in the combined text:", len(text))

The number of characters in the combined text: 122087065


In [6]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"#%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|~ ँंअआईउएकखगचछजझडढतथदनपफबमयरलवसह़ािीुूेैो्फ़ఁంఃఅఆఇఈఉఊఋఎఏఐఒఓఔకఖగఘఙచఛజఝఞటఠడఢణతథదధనపఫబభమయరఱలళవశషసహాిీుూృౄెేైొోౌ్ౖౠ౦౧౨౩౪౫౬౭౮౯‌‍‎‪�
220


In [7]:
#Data cleaning to only have telugu characters
def retain_telugu_and_special_combined(text):
    allowed_specials = set('!"#%&\'()*+,-./0123456789:;<=>?')
    return ''.join(
        c for c in text
        if ('\u0C00' <= c <= '\u0C7F') or c.isspace() or (c in allowed_specials)
    )

In [8]:
cleaned_text = retain_telugu_and_special_combined(text)

In [9]:
print("The number of characters in the cleaned text:", len(cleaned_text))

The number of characters in the cleaned text: 121953879


In [10]:
chars = sorted(list(set(cleaned_text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"#%&'()*+,-./0123456789:;<=>? ఁంఃఅఆఇఈఉఊఋఎఏఐఒఓఔకఖగఘఙచఛజఝఞటఠడఢణతథదధనపఫబభమయరఱలళవశషసహాిీుూృౄెేైొోౌ్ౖౠ౦౧౨౩౪౫౬౭౮౯
111


In [11]:
#create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

In [12]:
print(encode("సుశీలమ్మ కళ్ళలో భయం పారాడింది"))
print(decode(encode("సుశీలమ్మ కళ్ళలో భయం పారాడింది")))

[83, 88, 81, 87, 78, 74, 98, 74, 2, 50, 79, 98, 79, 78, 96, 2, 73, 75, 35, 2, 70, 85, 76, 85, 62, 86, 35, 67, 86]
సుశీలమ్మ కళ్ళలో భయం పారాడింది


In [13]:
import torch
data = torch.tensor(encode(cleaned_text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([121953879]) torch.int64
tensor([ 1,  0, 33, 33,  2, 33, 83, 88, 81, 87, 78, 74, 98, 74,  2, 50, 79, 98,
        79, 78, 96,  2, 73, 75, 35,  2, 70, 85, 76, 85, 62, 86, 35, 67, 86, 15,
         1,  0, 33, 33,  2, 33,  4, 37, 69, 85, 68,  2, 72, 86, 62, 98, 62,  2,
        37, 69, 86,  2, 55, 86, 69, 98, 69, 70, 98, 70, 88, 62, 93,  2, 65, 92,
        78, 86, 83, 98, 65, 93,  2, 74, 69,  2, 67, 52, 98, 52, 86, 76, 80, 85,
        62, 88,  2, 37, 78, 85,  2, 37, 76, 74, 76, 86, 50,  2, 78, 93, 50, 88,
        35, 62, 85,  2, 55, 69, 88, 80, 88, 52, 85,  2, 70, 92, 76, 86, 52, 93,
        80, 85, 62, 85, 32,  4,  2, 70, 88, 60, 98, 60, 92, 62, 88,  2, 67, 86,
        52, 88, 78, 88,  2, 83, 88, 81, 87, 78, 74, 98, 74,  2, 50, 35, 61, 35,
        78, 96,  2, 70, 78, 86, 50, 86, 35, 67, 86, 15,  1,  0, 33, 33,  2, 33,
         4, 37, 67, 86,  2, 74, 69, 35,  2, 70, 92, 35, 55, 93, 67, 85, 69, 98,
        69, 86,  2, 72, 60, 98, 60, 86,  2, 80, 88, 35, 60, 88, 35, 67, 86, 15,
    

In [14]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [15]:
block_size = 8
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([1]) the target: 0
when input is tensor([1, 0]) the target: 33
when input is tensor([ 1,  0, 33]) the target: 33
when input is tensor([ 1,  0, 33, 33]) the target: 2
when input is tensor([ 1,  0, 33, 33,  2]) the target: 33
when input is tensor([ 1,  0, 33, 33,  2, 33]) the target: 83
when input is tensor([ 1,  0, 33, 33,  2, 33, 83]) the target: 88
when input is tensor([ 1,  0, 33, 33,  2, 33, 83, 88]) the target: 81


In [16]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[50, 60, 93, 15,  2, 73, 85, 76],
        [15, 33, 33, 33,  2, 33, 37, 70],
        [76, 86, 70, 86, 35, 55, 85, 62],
        [61, 85, 69, 87, 78, 85, 13,  2]])
targets:
torch.Size([4, 8])
tensor([[60, 93, 15,  2, 73, 85, 76, 98],
        [33, 33, 33,  2, 33, 37, 70, 98],
        [86, 70, 86, 35, 55, 85, 62, 88],
        [85, 69, 87, 78, 85, 13,  2, 81]])
----
when input is [50] the target: 60
when input is [50, 60] the target: 93
when input is [50, 60, 93] the target: 15
when input is [50, 60, 93, 15] the target: 2
when input is [50, 60, 93, 15, 2] the target: 73
when input is [50, 60, 93, 15, 2, 73] the target: 85
when input is [50, 60, 93, 15, 2, 73, 85] the target: 76
when input is [50, 60, 93, 15, 2, 73, 85, 76] the target: 98
when input is [15] the target: 33
when input is [15, 33] the target: 33
when input is [15, 33, 33] the target: 33
when input is [15, 33, 33, 33] the target: 2
when input is [15, 33, 33, 33, 2] the target: 33
when input is [

In [17]:
print(xb) # our input to the transformer

tensor([[50, 60, 93, 15,  2, 73, 85, 76],
        [15, 33, 33, 33,  2, 33, 37, 70],
        [76, 86, 70, 86, 35, 55, 85, 62],
        [61, 85, 69, 87, 78, 85, 13,  2]])


In [30]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 64 # how many independent sequences will we process in parallel?
block_size = 256 # what is the maximum context length for predictions?
max_iters = 3000
eval_interval = 500
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2

In [19]:
# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

In [20]:
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

In [21]:
class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # input of size (batch, time-step, channels)
        # output of size (batch, time-step, head size)
        B,T,C = x.shape
        k = self.key(x)   # (B,T,hs)
        q = self.query(x) # (B,T,hs)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5 # (B, T, hs) @ (B, hs, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,hs)
        out = wei @ v # (B, T, T) @ (B, T, hs) -> (B, T, hs)
        return out

In [22]:
class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

In [23]:
class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

In [24]:
class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

In [25]:
class GPTLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

        # better init, not covered in the original GPT video, but important, will cover in followup video
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [26]:
model = GPTLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

10.824303 M parameters


In [27]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

In [31]:
for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

step 0: train loss 2.6922, val loss 2.6929
step 500: train loss 1.8841, val loss 1.8839
step 1000: train loss 1.6529, val loss 1.6499
step 1500: train loss 1.5533, val loss 1.5508
step 2000: train loss 1.4897, val loss 1.4855
step 2500: train loss 1.4521, val loss 1.4498
step 2999: train loss 1.4133, val loss 1.4139


In [32]:
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=500)[0].tolist()))


    చెయ్యి. కొత్తగా తిరిగి నేల్చుకుని తన వీరు కప్పియింటినేటపట్టుంది. దాన్నా, నాకు కెాదురిచెత్తే ఎన్ని అభిమందికి అన్యకం చె. ఐదుకెళ్ళి చెప్పు... టెల్రాండ్లు కోరికలాగా చూడడంతసుంది; రాయడు.
పాడులో చూసినట్లు కళ్ళకీటముందుకు ఒక చప్పున పంకజం, మొహం లేకుండా మత బలహీేళ్ళు.
భంజం బతుకుతో, హంతకురాల్ళో మూలంగా పట్టి.
నేటికి మందుని గొప్పగించింది కాబోతు!
పార్యేకంతో పచ్చింది.
నార్ధ్యాజికి ఎప్పుడొస్తే నీకు తెలిసింది.
మట్బల పొందడు నా ఇద్దంటార్ నీ అవుతూంది!
మా కేక్కింత బాగుంది, అనుమానం నీకుకాబోతూంది లోపలికి వెళ్
